index:
    path: /
    controller: App\Controller\IndexController::index

contact:
    path: /Contact
    controller: App\Controller\ContactController::addContact

register:
    path: /Register
    controller: App\Controller\RegistrationController::register

login:
    path: /Login
    controller: App\Controller\LoginController::index

logout:
    path: /Logout
    controller: App\Controller\SecurityController::logout

